In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [19]:
# Creating a 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array")
print(arr1)
print("")

# Creating a 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2d Array")
print(arr2)
print("")

# 3D Array
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3d Array")
print(arr3)

1D Array
[1 2 3 4 5]

2d Array
[[1 2 3]
 [4 5 6]]

3d Array
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
# Array Properties
import numpy as np
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr2.shape) # (2, 3) -> Rows, Columns
print(arr2.size) # Total number of elements
print(arr2.dtype) # Data type of elements

(2, 3)
6
int32


In [7]:
# Mathematical Operations

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b) # Element-wise addition
print(a - b) # Element-wise subtraction
print(a * b) # Element-wise multiplication
print(a / b) # Element-wise division
print(np.dot(a, b)) # Dot product

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
32


In [9]:
# Array Reshaping

arr = np.arange(1, 10)
reshaped = arr.reshape(3, 3) # Reshapes 1D array into 3x3 matrix

print(reshaped)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
# Indexing & Slicing

arr = np.array([10, 20, 30, 40, 50])

print(arr[1]) # 20 (Indexing)
print(arr[1:4]) # [20, 30, 40] (Slicing)

20
[20 30 40]


In [15]:
# Aggregation Functions

arr = np.array([10, 20, 30, 40])
print(np.sum(arr)) # Sum of elements
print(np.mean(arr)) # Mean of elements
print(np.std(arr)) # Standard deviation
print(np.min(arr)) # Minimum value
print(np.max(arr)) # Maximum value

100
25.0
11.180339887498949
10
40


In [17]:
# Matrix Multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
# Matrix multiplication
C = np.dot(A, B)
print(C)


[[19 22]
 [43 50]]


In [21]:
# 1D Array Slicing

arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4]) # [20 30 40] (Elements from index 1 to 3)
print(arr[:3]) # [10 20 30] (First three elements)
print(arr[::2]) # [10 30 50] (Every second element)

# 2D Array Slicing

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr[:2, 1:]) # Extracts first two rows, from second column onward

[20 30 40]
[10 20 30]
[10 30 50]
[[2 3]
 [5 6]]


In [23]:
# NumPy arrays have various attributes that describe their properties.

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.ndim) # Number of dimensions (2D → 2)
print(arr.shape) # Shape (Rows, Columns) → (2, 3)
print(arr.size) # Total number of elements → 6
print(arr.dtype) # Data type of elements → int
print(arr.itemsize) # Memory size of each element (bytes)

2
(2, 3)
6
int32
4


In [25]:
# Basic Arithmetic Operations in NumPy

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = arr1 + arr2 # Element-wise addition
print(result) # [5 7 9]

# Subtraction of Arrays
result = arr1 - arr2 # Element-wise subtraction
print(result) # [-3 -3 -3]

# Multiplication of Arrays
result = arr1 * arr2 # Element-wise multiplication
print(result) # [4 10 18]

# Division of Arrays
result = arr1 / arr2 # Element-wise division
print(result) # [0.25 0.4 0.5]

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
